### ISSUE TITLE
Crew, Attendance 테이블 분리

### ISSUE THREAD

**Issue by donghoony** [fromitive/java-wooteco-attendance#6]
현재 Attendance에서 너무 많은 책임을 가지고 있는 것으로 보여집니다. `null`을 활용해 출석 여부를 확인하는 것도 그렇고요.
Crew를 따로 저장하는 게 좋아 보여서 이슈로 남겨 둡니다

**Comment by fromitive** [comment]
GoogleCralwer가 크롤링 할 때 마다 이미 가져온 데이터를 갖고 오기 때문에 업데이트하는 전략이 적절한 선택이라고 판단했습니다.

이부분은 `크롤링의 방식` 혹은 `출석 데이터 저장 방법`을 변경을 해서 null 값과 업데이트를  허용하지 않는 방향으로 가보는건 어떨까요?

**Comment by donghoony** [comment]
크루들의 출석을 모니터링하기 위한 어플리케이션에서 **크루**와 **출석**이 서로 다른 관심사라고 느껴져서요! 비록 크롤러 입장에서 확인한다면 불필요할 수 있지만, 추후 확장 가능성이나 문제 해결의 관점에서 바라본다면 크루를 뽑아두는 게 테스트나 의존성 측에서도 도움되리라 생각돼요. 크롤러라는 외부 API에 의존하는 것을 크루를 뽑아내 크루 도메인 / 출석 확인 도메인으로 나눠 출석 확인에서만 크롤러가 의존하도록 할 수 있고요.
